services:
  postgres:
    image: postgres:16
    container_name: de_postgres
    environment:
      POSTGRES_USER: de
      POSTGRES_PASSWORD: de
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: de_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  airflow-init:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: de_airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de:de@postgres:5432/warehouse
    volumes:
      - airflow_logs:/opt/airflow/logs
      - airflow_dags:/opt/airflow/dags
    command: >
      bash -lc "
      airflow db migrate &&
      airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: de_airflow_web
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de:de@postgres:5432/warehouse
      DBT_PROFILES_DIR: /opt/airflow/repo/dbt
      REPO_ROOT: /opt/airflow/repo
    ports:
      - "8080:8080"
    volumes:
      - airflow_logs:/opt/airflow/logs
      - airflow_dags:/opt/airflow/dags
      - C:\Dev\GitHub\nyc-taxi-de\airflow\dags:/opt/airflow/dags
      - C:\Dev\GitHub\nyc-taxi-de:/opt/airflow/repo
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: de_airflow_sched
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de:de@postgres:5432/warehouse
      DBT_PROFILES_DIR: /opt/airflow/repo/dbt
      REPO_ROOT: /opt/airflow/repo
    volumes:
      - airflow_logs:/opt/airflow/logs
      - airflow_dags:/opt/airflow/dags
      - C:\Dev\GitHub\nyc-taxi-de\airflow\dags:/opt/airflow/dags
      - C:\Dev\GitHub\nyc-taxi-de:/opt/airflow/repo
    command: scheduler

volumes:
  pgdata:
  miniodata:
  airflow_logs:
  airflow_dags: